
# @name gettoken
POST https://localhost:8001/api/users/token
Content-Type: application/json

{
    "username": "admin",
    "password": "P@ssw0rd!",
    "admin": "true"
}

### Get token
@token = {{gettoken.response.body.token}}


### Create a token
# @name temptoken
POST https://localhost:8001/api/admin/token/addtokenbytype
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "UrlTokenType": "AllowAddUser"
}

### Get st bild id
@url-token = {{temptoken.response.body.token}}
@url-token-id = {{temptoken.response.body.id}}

### Delete token
DELETE https://localhost:8001/api/admin/token/{{url-token-id}}
Authorization: Bearer {{token}}

### Get token
GET https://localhost:8001/api/admin/token/{{url-token}}
Authorization: Bearer {{token}}

### Get all valid tokens
GET https://localhost:8001/api/admin/token/valid-tokens
Authorization: Bearer {{token}}