### Create a user
# @password = P@ssw0rd!

# POST http://localhost:5000/users
# Content-Type: application/json

# {
#     "username": "myuser",
#     "password": "{{password}}"
# }

# @name gettoken
POST https://localhost:8001/api/users/token
Content-Type: application/json

{
    "username": "admin",
    "password": "P@ssw0rd!",
    "admin": "true"
}

### Get token
@token = {{gettoken.response.body.token}}

### Pre-create user
POST https://localhost:8001/api/admin/users/precreate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "nils@kalledomain.com"
}

### Get all users
POST https://localhost:8001/api/users/bytoken
Content-Type: application/json

{
  "token": "{{token}}"
}

### Get all users
GET https://localhost:8001/api/admin/users
Authorization: Bearer {{token}}
Content-Type: application/json


### Create a token
# @name temptoken
POST http://localhost:5000/api/admin/token/addtokenbytype
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "UrlTokenType": "AllowAddUser"
}

### Get st bild id
@url-token = {{temptoken.response.body.token}}
@url-token-id = {{temptoken.response.body.id}}

### Create token and user providing a url token
POST http://localhost:5000/api/users/token/Google
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "user@somedomain.com",
  "providerKey": "somekey",
  "urlToken": "{{url-token}}"
}

### Create user providing a url token
# @name newuser
POST http://localhost:5000/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "bernt",
  "password": "P@ssw0rd!",
  "isAdmin": true,
  "email": "nisse@ksksk.se",
  "urlToken": "{{url-token}}"
}

### Update user
PUT http://localhost:5000/api/admin/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": "4d672e7e-75ed-48c2-aeb4-bf83ecfb2cd1",
    "userName": "bernt",
    "firstName": "Bernt",
    "lastName": "Johansson",
    "email": "tomas@hellstroms.org",
    "isAdmin": true
}

### Get user by username
GET http://localhost:5000/api/admin/user/admin
Authorization: Bearer {{token}}
Content-Type: application/json

### Get user by username
DELETE http://localhost:5000/api/admin/user/bernt
Authorization: Bearer {{token}}
Content-Type: application/json

