apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fotowebb-images
spec:
  storageClassName: "" # same storage class as pvc
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4 # ip addres of nfs server
    path: "/mnt/storage/k8s/fotowebb/images" # path to directory

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fotowebb-cert
spec:
  storageClassName: "" # same storage class as pvc
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4 # ip addres of nfs server
    path: "/mnt/storage/k8s/fotowebb/cert" # path to directory

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fotowebb-db
spec:
  storageClassName: "" # same storage class as pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4 # ip addres of nfs server
    path: "/mnt/storage/k8s/fotowebb/db" # path to directory

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fotowebb-postgres
spec:
  storageClassName: "" # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4 # ip addres of nfs server
    path: "/mnt/storage/k8s/fotowebb/postgres" # path to directory