kind: Service
apiVersion: v1
metadata:
  name: fotowebb-loadbalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
spec:
  ports:
    - name: 'letsecnrypt'
      protocol: TCP
      port: 8180
      targetPort: 80
    - name: 'api'
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: 'web'
      protocol: TCP
      port: 8002
      targetPort: 8002
  selector:
    name: fotowebb
  type: LoadBalancer
  loadBalancerIP: 10.10.20.230

