apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-fotowebb-images
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 50Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-fotowebb-cert
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Mi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-fotowebb-db
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 5Gi