kind: Deployment
apiVersion: apps/v1
metadata:
  name: fotowebb-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fotowebb-db
  template:
    metadata:
      name: fotowebb-db
      labels:
        name: fotowebb-db
    spec:
      volumes:
        - name: nfs-fotowebb-cert
          persistentVolumeClaim:
            claimName: nfs-fotowebb-cert
        - name: nfs-fotowebb-postgres
          persistentVolumeClaim:
            claimName: nfs-fotowebb-postgres
      # securityContext:
      #       runAsUser: 70
      #       supplementalGroups: [999,1000]
      #       fsGroup: 70
      containers:
        - name: database
          image: 'postgres:15.3-alpine'
          command: ["/cert/script/init_postgres.sh"]
          env:
            - name: POSTGRES_USER
              value: "fotowebb"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fotowebb
                  key: postgres-password
            # - name: POSTGRES_HOST_AUTH_METHOD
            #   value: "trust"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: nfs-fotowebb-cert
              mountPath: /cert
              
            - name: nfs-fotowebb-postgres
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
