name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
    - name: dotnet build
      run: dotnet build ./FotoApp.sln -c Release

    - name: dotnet test
      run: dotnet test ./FotoApp.sln -c Release --no-build --results-directory TestResults --logger trx
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Dotnet Tests          # Name of the check run which will be created
        path: TestResults/*.xml     # Path to test results
        reporter: dotnet-trx        # Format of test results